name: Java Selenium CI

on:
  push:
    branches: [ "master" ]   # Run when pushing to master
  pull_request:
    branches: [ "master" ]   # Run on PRs to master
  schedule:
   - cron: "30 18 * * 4"   # Every Friday 12:00 AM IST


jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean

      - name: Run Smoke Tests
        run: mvn test -PST

  regression:
    runs-on: ubuntu-latest
    needs: smoke   # <-- Only runs if smoke passes

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean

      - name: Run Regression Tests
        run: mvn test -PRT
